baseURL = 'http://example.org/'
title = 'MLabs'


# theme = 'LoveIt'
theme = ['hugo-shortcode-roneo-collection', 'LoveIt']


# Language
defaultContentLanguage = "ru"

[languages]
  [languages.en]
    weight = 1
    title = "MLabs"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "blog"
      pre = ""
      post = ""
      name = "Blog"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "courses"
      pre = ""
      post = ""
      name = "Courses"
      url = "/courses/"
      title = ""
    # [[languages.en.menu.main]]
    #   weight = 2
    #   identifier = "researches"
    #   pre = ""
    #   post = ""
    #   name = "Researches"
    #   url = "/researches/"
    #   title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "events"
      pre = " "
      post = ""
      name = "Events"
      url = "/calendar.html/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""

  [languages.ru]
    weight = 2
    title = "MLabs"
    languageCode = "ru"
    languageName = "Russian"
    [[languages.ru.menu.main]]
      weight = 1
      identifier = "blog"
      pre = ""
      post = ""
      name = "Блог"
      url = "/posts/"
      title = ""
    [[languages.ru.menu.main]]
      weight = 2
      identifier = "courses"
      name = "Курсы"
      pre = ""
      post = ""
      url = "/courses/"
      title = ""
    # [[languages.ru.menu.main]]
    #   weight = 2
    #   identifier = "researches"
    #   name = "Исследования"
    #   pre = ""
    #   post = ""
    #   url = "/researches/"
    #   title = ""
    [[languages.ru.menu.main]]
      weight = 3
      identifier = "events"
      name = "Мероприятия"
      pre = ""
      post = ""
      url = "/calendar.html/"
      title = ""
    [[languages.ru.menu.main]]
      weight = 4
      identifier = "tags"
      pre = ""
      post = ""
      name = "Тэги"
      url = "/tags/"
      title = ""


# Author config
[author]
  name = "MLabs"
  email = "mlnchkdv@gmail.com"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  # [[menu.main]]
  #   weight = 2
  #   identifier = "researches"
  #   pre = ""
  #   post = ""
  #   name = "Researches"
  #   url = "/researches/"
  #   title = ""
  [[menu.main]]
    weight = 3
    identifier = "events"
    pre = ""
    post = ""
    name = "Events"
    url = "/calendar.html/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  # [[menu.main]]
  #   weight = 4
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "Categories"
  #   url = "/categories/"
  #   title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files

[Permalinks]
  # posts = ":year/:month/:filename"
  # posts = ":filename"
  posts = "/blog/:slug"